from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path


HFP_PROFILE_HINTS = ("headset", "handsfree", "hands-free", "hfp", "hsp", "audio-gateway")
IDLE_AUDIO_PROFILE = "off"
PHONE_SAFE_WIREPLUMBER_CONFIG = """# Generated by Linkable.
# Phone-safe Bluetooth mode: do not advertise this laptop as an A2DP media sink.
# This prevents phones from routing YouTube/media audio to the laptop while
# preserving laptop-to-headset A2DP source and HFP call-audio roles.
monitor.bluez.properties = {
  bluez5.roles = [ a2dp_source hfp_hf hfp_ag ]
  bluez5.auto-connect = [ hfp_hf hfp_ag ]
}
"""
PHONE_SAFE_CONFIG_PATH = Path.home() / ".config" / "wireplumber" / "wireplumber.conf.d" / "52-linkable-phone-safe-bluetooth.conf"


@dataclass(frozen=True)
class CommandResult:
    command: tuple[str, ...]
    returncode: int
    stdout: str
    stderr: str

    @property
    def ok(self) -> bool:
        return self.returncode == 0

    def compact_output(self) -> str:
        output = "\n".join(part for part in (self.stdout.strip(), self.stderr.strip()) if part)
        return output or f"exit={self.returncode}"


@dataclass(frozen=True)
class BluetoothAdapterStatus:
    available: bool
    powered: bool = False
    discoverable: bool = False
    pairable: bool = False
    alias: str = ""
    address: str = ""
    detail: str = ""


@dataclass(frozen=True)
class AudioStackStatus:
    pactl_available: bool
    wpctl_available: bool
    pipewire_available: bool
    wireplumber_available: bool
    server_name: str = ""
    hfp_cards: tuple[str, ...] = ()
    detail: str = ""


@dataclass(frozen=True)
class PhoneSafeBluetoothStatus:
    installed: bool
    config_path: Path = PHONE_SAFE_CONFIG_PATH
    active_without_restart: bool = False
    detail: str = ""


@dataclass(frozen=True)
class BluetoothDevice:
    address: str
    name: str
    paired: bool = False
    trusted: bool = False
    connected: bool = False


@dataclass(frozen=True)
class BluetoothAudioCard:
    name: str
    profiles: tuple[str, ...]
    alias: str = ""
    description: str = ""
    address: str = ""
    active_profile: str = ""

    @property
    def label(self) -> str:
        identity = self.alias or self.description or self.address or self.name
        profile_text = ", ".join(self.hfp_profiles()) or "no HFP profile"
        return f"{self.name} ({identity}) -> {profile_text}"

    def hfp_profiles(self) -> tuple[str, ...]:
        return tuple(profile for profile in self.profiles if is_hfp_profile(profile))

    def matches_identity(self, identity: str) -> bool:
        normalized = normalize_identity(identity)
        if not normalized:
            return False
        candidates = {
            self.name,
            self.alias,
            self.description,
            self.address,
            self.address.replace(":", "_"),
            self.name.replace("bluez_card.", "").replace("_", ":"),
        }
        for candidate in candidates:
            candidate_normalized = normalize_identity(candidate)
            if candidate_normalized and (
                candidate_normalized == normalized
                or normalized in candidate_normalized
                or candidate_normalized in normalized
            ):
                return True
        return False


@dataclass(frozen=True)
class HfpStatus:
    adapter: BluetoothAdapterStatus
    audio: AudioStackStatus
    devices: tuple[BluetoothDevice, ...] = ()
    phone_safe: PhoneSafeBluetoothStatus = field(default_factory=lambda: PhoneSafeBluetoothStatus(installed=False))
    notes: tuple[str, ...] = field(default_factory=tuple)

    @property
    def ready_for_pairing(self) -> bool:
        return self.adapter.available and self.adapter.powered and self.adapter.discoverable and self.adapter.pairable

    @property
    def hfp_audio_ready(self) -> bool:
        return self.audio.pipewire_available and self.audio.wireplumber_available and bool(self.audio.hfp_cards)

    def format(self) -> str:
        lines = [
            "Bluetooth HFP audio status",
            (
                "adapter: "
                f"available={self.adapter.available}, powered={self.adapter.powered}, "
                f"pairable={self.adapter.pairable}, discoverable={self.adapter.discoverable}"
            ),
        ]
        if self.adapter.alias or self.adapter.address:
            lines.append(f"adapter identity: {self.adapter.alias or 'unknown'} {self.adapter.address}".strip())
        if self.adapter.detail:
            lines.append(f"adapter detail: {self.adapter.detail}")
        lines.append(
            "audio stack: "
            f"pipewire={self.audio.pipewire_available}, wireplumber={self.audio.wireplumber_available}, "
            f"pactl={self.audio.pactl_available}, wpctl={self.audio.wpctl_available}"
        )
        if self.audio.server_name:
            lines.append(f"audio server: {self.audio.server_name}")
        if self.audio.hfp_cards:
            lines.append("HFP-capable cards:")
            lines.extend(f"- {card}" for card in self.audio.hfp_cards)
        else:
            lines.append("HFP-capable cards: none detected yet")
        lines.append(
            "phone-safe Bluetooth mode: "
            f"installed={self.phone_safe.installed}, path={self.phone_safe.config_path}"
        )
        if self.phone_safe.detail:
            lines.append(f"phone-safe detail: {self.phone_safe.detail}")
        if self.devices:
            lines.append("Bluetooth devices:")
            lines.extend(
                f"- {device.address} {device.name} paired={device.paired} trusted={device.trusted} connected={device.connected}"
                for device in self.devices
            )
        else:
            lines.append("Bluetooth devices: none listed")
        lines.extend(f"note: {note}" for note in self.notes)
        return "\n".join(lines)


class HfpManager:
    """Controls Linux Bluetooth HFP through BlueZ plus PipeWire/PulseAudio commands.

    This intentionally avoids implementing an audio transport. SIM-call audio is routed by
    the OS Bluetooth stack after the phone pairs with this laptop as a headset/car-kit.
    """

    def status(self) -> HfpStatus:
        adapter = self.adapter_status()
        audio = self.audio_status()
        devices = tuple(self.bluetooth_devices()) if adapter.available else ()
        notes: list[str] = []
        if not adapter.available:
            notes.append("Install/start BlueZ and run this app in a session with D-Bus access.")
        elif not adapter.powered:
            notes.append("Bluetooth adapter is not powered; turn it on in the Linux Bluetooth settings.")
        elif not adapter.discoverable or not adapter.pairable:
            notes.append("Pair manually from the normal Linux and Android Bluetooth settings when needed.")
        if not audio.pipewire_available or not audio.wireplumber_available:
            notes.append("PipeWire and WirePlumber are recommended for Bluetooth HFP/HSP audio routing.")
        if not audio.hfp_cards:
            notes.append("No phone HFP card is visible yet; pair/connect the phone manually first.")
        phone_safe = self.phone_safe_status()
        if adapter.available and self.adapter_exposes_media_audio_sink():
            if phone_safe.installed:
                notes.append("Phone-safe mode is installed but A2DP sink is still advertised; restart WirePlumber/PipeWire or reconnect Bluetooth.")
            else:
                notes.append("This laptop still advertises A2DP media sink; install phone-safe Bluetooth mode to prevent phone media routing here.")
        notes.append("LAN remains responsible for metadata/control; Bluetooth is only switched into HFP for desktop-handled SIM calls.")
        return HfpStatus(adapter=adapter, audio=audio, devices=devices, phone_safe=phone_safe, notes=tuple(notes))

    def adapter_status(self) -> BluetoothAdapterStatus:
        if shutil.which("bluetoothctl") is None:
            return BluetoothAdapterStatus(available=False, detail="bluetoothctl not found")
        result = run_command(("bluetoothctl", "show"))
        if not result.ok:
            return BluetoothAdapterStatus(available=False, detail=result.compact_output())
        values = parse_key_values(result.stdout)
        address = parse_controller_address(result.stdout)
        discoverable = parse_bool(values.get("Discoverable", "")) or parse_bool(values.get("Discovering", ""))
        return BluetoothAdapterStatus(
            available=True,
            powered=parse_bool(values.get("Powered", "")),
            discoverable=discoverable,
            pairable=parse_bool(values.get("Pairable", "")),
            alias=values.get("Alias", ""),
            address=address,
            detail="ok",
        )

    def adapter_exposes_media_audio_sink(self) -> bool:
        if shutil.which("bluetoothctl") is None:
            return False
        result = run_command(("bluetoothctl", "show"))
        if not result.ok:
            return False
        return "Audio Sink" in result.stdout

    def phone_safe_status(self) -> PhoneSafeBluetoothStatus:
        if not PHONE_SAFE_CONFIG_PATH.exists():
            return PhoneSafeBluetoothStatus(installed=False, detail="not installed")
        try:
            content = PHONE_SAFE_CONFIG_PATH.read_text(encoding="utf-8")
        except OSError as exc:
            return PhoneSafeBluetoothStatus(installed=True, detail=f"cannot read config: {exc}")
        expected = PHONE_SAFE_WIREPLUMBER_CONFIG.strip()
        detail = "installed by Linkable" if content.strip() == expected else "custom file exists at Linkable config path"
        return PhoneSafeBluetoothStatus(
            installed=True,
            active_without_restart=not self.adapter_exposes_media_audio_sink(),
            detail=detail,
        )

    def install_phone_safe_mode(self) -> CommandResult:
        try:
            PHONE_SAFE_CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
            PHONE_SAFE_CONFIG_PATH.write_text(PHONE_SAFE_WIREPLUMBER_CONFIG, encoding="utf-8")
        except OSError as exc:
            return CommandResult(
                command=("write", str(PHONE_SAFE_CONFIG_PATH)),
                returncode=1,
                stdout="",
                stderr=str(exc),
            )
        restart = self.restart_audio_services()
        return CommandResult(
            command=("install-phone-safe-bluetooth",),
            returncode=restart.returncode,
            stdout=f"Installed {PHONE_SAFE_CONFIG_PATH}\n{restart.stdout}".strip(),
            stderr=restart.stderr,
        )

    def remove_phone_safe_mode(self) -> CommandResult:
        try:
            if PHONE_SAFE_CONFIG_PATH.exists():
                PHONE_SAFE_CONFIG_PATH.unlink()
        except OSError as exc:
            return CommandResult(
                command=("remove", str(PHONE_SAFE_CONFIG_PATH)),
                returncode=1,
                stdout="",
                stderr=str(exc),
            )
        restart = self.restart_audio_services()
        return CommandResult(
            command=("remove-phone-safe-bluetooth",),
            returncode=restart.returncode,
            stdout=f"Removed {PHONE_SAFE_CONFIG_PATH}\n{restart.stdout}".strip(),
            stderr=restart.stderr,
        )

    def restart_audio_services(self) -> CommandResult:
        if shutil.which("systemctl") is None:
            return CommandResult(
                command=("systemctl", "--user", "restart", "wireplumber", "pipewire", "pipewire-pulse"),
                returncode=1,
                stdout="",
                stderr="systemctl not found; restart WirePlumber/PipeWire or reboot.",
            )
        return run_command(
            ("systemctl", "--user", "restart", "wireplumber", "pipewire", "pipewire-pulse"),
            timeout=15,
        )

    def audio_status(self) -> AudioStackStatus:
        pactl_available = shutil.which("pactl") is not None
        wpctl_available = shutil.which("wpctl") is not None
        pipewire_available = shutil.which("pipewire") is not None
        wireplumber_available = shutil.which("wireplumber") is not None
        server_name = ""
        detail = ""
        if pactl_available:
            info = run_command(("pactl", "info"))
            if info.ok:
                values = parse_key_values(info.stdout)
                server_name = values.get("Server Name", "")
                if "pipewire" in server_name.lower():
                    pipewire_available = True
            else:
                detail = info.compact_output()
        return AudioStackStatus(
            pactl_available=pactl_available,
            wpctl_available=wpctl_available,
            pipewire_available=pipewire_available,
            wireplumber_available=wireplumber_available,
            server_name=server_name,
            hfp_cards=tuple(self.hfp_cards()) if pactl_available else (),
            detail=detail,
        )

    def bluetooth_devices(self) -> list[BluetoothDevice]:
        paired = parse_bluetooth_device_lines(run_command(("bluetoothctl", "devices", "Paired")).stdout)
        connected = {device.address for device in parse_bluetooth_device_lines(run_command(("bluetoothctl", "devices", "Connected")).stdout)}
        all_devices = parse_bluetooth_device_lines(run_command(("bluetoothctl", "devices")).stdout)
        by_address = {device.address: device for device in all_devices}
        for device in paired:
            by_address[device.address] = BluetoothDevice(
                address=device.address,
                name=device.name,
                paired=True,
                trusted=self.device_flag(device.address, "Trusted"),
                connected=device.address in connected or self.device_flag(device.address, "Connected"),
            )
        for address in connected:
            if address in by_address and not by_address[address].connected:
                device = by_address[address]
                by_address[address] = BluetoothDevice(
                    address=device.address,
                    name=device.name,
                    paired=device.paired,
                    trusted=device.trusted,
                    connected=True,
                )
        return sorted(by_address.values(), key=lambda device: (not device.connected, not device.paired, device.name))

    def device_flag(self, address: str, field_name: str) -> bool:
        result = run_command(("bluetoothctl", "info", address))
        if not result.ok:
            return False
        values = parse_key_values(result.stdout)
        return parse_bool(values.get(field_name, ""))

    def hfp_cards(self) -> list[str]:
        return [card.label for card in self.hfp_audio_cards()]

    def bluetooth_audio_cards(self) -> dict[str, list[str]]:
        cards = parse_pactl_card_profiles(run_command(("pactl", "list", "cards")).stdout)
        return {name: profiles for name, profiles in cards.items() if name.startswith("bluez_card")}

    def bluetooth_audio_card_infos(self) -> list[BluetoothAudioCard]:
        cards = parse_pactl_card_infos(run_command(("pactl", "list", "cards")).stdout)
        return [card for card in cards if card.name.startswith("bluez_card")]

    def hfp_audio_cards(self) -> list[BluetoothAudioCard]:
        return [card for card in self.bluetooth_audio_card_infos() if card.hfp_profiles()]

    def call_audio_card_for_device(self, device_identity: str) -> BluetoothAudioCard | None:
        normalized = normalize_identity(device_identity)
        if not normalized:
            return None
        cards = self.hfp_audio_cards()
        for card in cards:
            if card.matches_identity(device_identity):
                return card
        for device in self.bluetooth_devices():
            if normalize_identity(device.name) == normalized:
                for card in cards:
                    if card.matches_identity(device.address):
                        return card
        return None

    def select_idle_profile(self, card_name: str | None = None) -> CommandResult:
        if card_name is None:
            return CommandResult(
                command=("pactl", "set-card-profile", "<phone-bluez-card>", IDLE_AUDIO_PROFILE),
                returncode=1,
                stdout="",
                stderr="Refusing to change every Bluetooth audio card; provide the matched phone card.",
            )
        cards = self.bluetooth_audio_cards()
        candidates = [
            name
            for name in cards
            if name == card_name
        ]
        if not candidates:
            target = card_name or "any bluez_card"
            return CommandResult(
                command=("pactl", "set-card-profile", target, IDLE_AUDIO_PROFILE),
                returncode=1,
                stdout="",
                stderr=f"No Bluetooth audio card detected for {target}. Pair/connect the phone first.",
            )
        results = [
            run_command(("pactl", "set-card-profile", name, IDLE_AUDIO_PROFILE), timeout=10)
            for name in candidates
        ]
        return combine_results(("pactl", "set-card-profile", "<bluez_card>", IDLE_AUDIO_PROFILE), results)

    def enable_call_audio_profile(self, card_name: str | None = None) -> CommandResult:
        return self.select_hfp_profile(card_name=card_name)

    def disable_call_audio_profile(self, card_name: str | None = None) -> CommandResult:
        return self.select_idle_profile(card_name=card_name)

    def select_hfp_profile(self, card_name: str | None = None) -> CommandResult:
        if card_name is None:
            return CommandResult(
                command=("pactl", "set-card-profile", "<phone-bluez-card>", "<hfp-profile>"),
                returncode=1,
                stdout="",
                stderr="Refusing to select an arbitrary Bluetooth audio card; provide the matched phone card.",
            )
        cards = parse_pactl_cards(run_command(("pactl", "list", "cards")).stdout)
        candidates = [
            (name, profiles)
            for name, profiles in cards.items()
            if name.startswith("bluez_card") and name == card_name
        ]
        for name, profiles in candidates:
            profile = first_hfp_profile(profiles)
            if profile is not None:
                return run_command(("pactl", "set-card-profile", name, profile), timeout=10)
        target = card_name or "any bluez_card"
        return CommandResult(
            command=("pactl", "set-card-profile", target, "<hfp-profile>"),
            returncode=1,
            stdout="",
            stderr=f"No available HFP/HSP profile detected for {target}. Pair/connect the phone first.",
        )


def combine_results(command: tuple[str, ...], results: list[CommandResult]) -> CommandResult:
    stdout = "\n".join(result.compact_output() for result in results if result.compact_output())
    stderr = "\n".join(result.stderr.strip() for result in results if result.stderr.strip() and not result.ok)
    return CommandResult(
        command=command,
        returncode=0 if all(result.ok for result in results) else 1,
        stdout=stdout,
        stderr=stderr,
    )

def run_command(
    command: tuple[str, ...],
    *,
    input_text: str | None = None,
    timeout: int = 5,
) -> CommandResult:
    try:
        completed = subprocess.run(
            command,
            input=input_text,
            text=True,
            capture_output=True,
            timeout=timeout,
            check=False,
        )
        return CommandResult(
            command=command,
            returncode=completed.returncode,
            stdout=completed.stdout,
            stderr=completed.stderr,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return CommandResult(command=command, returncode=1, stdout="", stderr=str(exc))


def parse_key_values(text: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        values[key.strip()] = value.strip()
    return values


def parse_controller_address(text: str) -> str:
    for line in text.splitlines():
        match = re.match(r"\s*Controller\s+([0-9A-Fa-f:]{17})\b", line)
        if match is not None:
            return match.group(1).upper()
    values = parse_key_values(text)
    candidate = values.get("Controller", "").split(" ", 1)[0]
    return candidate.upper() if re.fullmatch(r"[0-9A-Fa-f:]{17}", candidate) else ""


def parse_bool(value: str) -> bool:
    return value.strip().lower() in {"yes", "true", "1", "on"}


def parse_bluetooth_device_lines(text: str) -> list[BluetoothDevice]:
    devices: list[BluetoothDevice] = []
    for line in text.splitlines():
        match = re.match(r"Device\s+([0-9A-Fa-f:]{17})\s+(.+)", line.strip())
        if match is None:
            continue
        devices.append(BluetoothDevice(address=match.group(1).upper(), name=match.group(2).strip()))
    return devices


def validate_bluetooth_address(address: str) -> None:
    if re.fullmatch(r"[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){5}", address.strip()) is None:
        raise ValueError("Bluetooth address must look like AA:BB:CC:DD:EE:FF")


def normalize_identity(value: str) -> str:
    return re.sub(r"[^0-9a-z]+", "", value.strip().lower())


def is_hfp_profile(profile: str) -> bool:
    return any(hint in profile.lower() for hint in HFP_PROFILE_HINTS)


def address_from_bluez_card_name(name: str) -> str:
    match = re.match(r"bluez_card\.([0-9A-Fa-f_]{17})", name)
    return match.group(1).replace("_", ":").upper() if match is not None else ""


def parse_pactl_card_infos(text: str) -> list[BluetoothAudioCard]:
    cards: list[dict[str, object]] = []
    current: dict[str, object] | None = None
    in_profiles = False

    def finish_current() -> None:
        if current is not None and current.get("name"):
            cards.append(current.copy())

    for raw_line in text.splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()
        if stripped.startswith("Card #"):
            finish_current()
            current = {"name": "", "profiles": [], "alias": "", "description": "", "address": "", "active_profile": ""}
            in_profiles = False
            continue
        if current is None:
            continue
        if stripped.startswith("Name:"):
            current["name"] = stripped.split(":", 1)[1].strip()
            continue
        if stripped == "Profiles:":
            in_profiles = True
            continue
        if stripped in {"Ports:", "Properties:"}:
            in_profiles = False
        if stripped.startswith("Active Profile:"):
            in_profiles = False
            current["active_profile"] = stripped.split(":", 1)[1].strip()
            continue
        property_match = re.match(r"([A-Za-z0-9_.-]+)\s*=\s*\"?(.+?)\"?$", stripped)
        if property_match is not None:
            key, value = property_match.group(1), property_match.group(2).strip()
            if key in {"device.alias", "bluez5.alias"}:
                current["alias"] = value
            elif key in {"device.description", "media.name"}:
                current["description"] = value
            elif key in {"api.bluez5.address", "bluez5.address"}:
                current["address"] = value.upper()
        if current.get("name") and in_profiles:
            profile_match = re.match(r"([A-Za-z0-9_.+-]+):\s+(.+)", stripped)
            if profile_match is None:
                continue
            profile_name = profile_match.group(1)
            detail = profile_match.group(2).lower()
            if "available: no" not in detail:
                profiles = current.setdefault("profiles", [])
                assert isinstance(profiles, list)
                profiles.append(profile_name)
    finish_current()

    infos: list[BluetoothAudioCard] = []
    for card in cards:
        name = str(card.get("name", ""))
        address = str(card.get("address", "")) or address_from_bluez_card_name(name)
        profiles = tuple(str(profile) for profile in card.get("profiles", []))
        infos.append(
            BluetoothAudioCard(
                name=name,
                profiles=profiles,
                alias=str(card.get("alias", "")),
                description=str(card.get("description", "")),
                address=address,
                active_profile=str(card.get("active_profile", "")),
            )
        )
    return infos


def parse_pactl_card_profiles(text: str) -> dict[str, list[str]]:
    return {card.name: list(card.profiles) for card in parse_pactl_card_infos(text) if card.profiles}


def parse_pactl_cards(text: str) -> dict[str, list[str]]:
    cards = parse_pactl_card_profiles(text)
    return {
        name: [
            profile
            for profile in profiles
            if is_hfp_profile(profile)
        ]
        for name, profiles in cards.items()
        if any(is_hfp_profile(profile) for profile in profiles)
    }


def first_hfp_profile(profiles: list[str]) -> str | None:
    preference = ("headset-head-unit-msbc", "headset-head-unit-cvsd", "headset-head-unit", "handsfree_head_unit", "audio-gateway")
    lowered = {profile.lower(): profile for profile in profiles}
    for preferred in preference:
        for profile_lower, profile in lowered.items():
            if preferred in profile_lower:
                return profile
    return profiles[0] if profiles else None
