from __future__ import annotations


STRINGS: dict[str, str] = {
    "app.title": "Linkable",
    "app.subtitle": "Phone as a trusted Linux peripheral",
    "startup.title": "Startup Check",
    "startup.intro": "Linkable checked this Linux desktop before starting the main app.",
    "startup.pass": "Ready",
    "startup.fail": "Needs attention",
    "startup.summary.fail": "{failed} failed, {critical} required",
    "startup.critical": "Required",
    "startup.optional": "Can skip",
    "startup.copy": "Copy",
    "startup.recheck": "Recheck",
    "startup.continue": "Continue",
    "startup.continue_anyway": "Continue anyway",
    "startup.skip": "Skip non-critical",
    "startup.exit": "Exit",
    "startup.sudo": "Run with sudo",
    "startup.user": "Run as your user",
    "wizard.title": "First-run setup",
    "wizard.intro": "Finish these setup choices once. They can be changed later.",
    "wizard.autostart": "Start LAN service on login",
    "wizard.autostart.detail": "A systemd user service keeps discovery available after login without launching the GUI.",
    "wizard.install": "Install service",
    "wizard.skip": "Skip for now",
    "wizard.notification": "Notification access",
    "wizard.notification.detail": "Confirm that your desktop notification daemon allows Linkable notifications.",
    "wizard.ssid": "Safe-listed Wi-Fi",
    "wizard.ssid.missing": "No active Wi-Fi SSID detected",
    "wizard.finish": "Finish setup",
    "wizard.copy.unit": "Copy unit file",
    "wizard.copy.command": "Copy install command",
    "wizard.install.ok": "Autostart service installed.",
    "wizard.install.error": "Autostart install failed: {error}",
    "wizard.command": "Install command",
    "wizard.unit": "Unit file",
    "main.service.starting": "Starting service...",
    "main.service.running": "LAN service running",
    "main.service.failed": "Service failed",
    "main.service.toggle": "LAN Service",
    "main.service.off": "xxxx..",
    "main.endpoint": "Endpoint",
    "main.device_id": "Device ID",
    "main.refresh": "Refresh",
    "main.logs.show": "Show logs",
    "main.logs.hide": "Hide logs",
    "nav.devices": "Devices",
    "nav.notifications": "Notifications",
    "nav.shared_apps": "Shared Apps",
    "nav.files": "Files",
    "nav.mirror": "Mirror",
    "nav.settings": "Phone Call",
    "nav.pending": "{panel} will be enabled after its backend is migrated into the new desktop shell.",
    "home.add_devices": "+ Add Devices",
    "home.wifi_access": "Wi-Fi Access",
    "home.wifi_all": "All",
    "home.wifi_safelisted": "Safelisted",
    "home.empty.title": "No devices yet",
    "home.empty.body": "Add a phone from the same Wi-Fi network to start using Linkable.",
    "home.quick_hint": "Common actions are available directly on each device card.",
    "devices.title": "Devices",
    "devices.subtitle": "Trusted phones and their current LAN/Bluetooth status.",
    "devices.pair": "Pair new phone",
    "devices.pair.ready": "Pairing is open for 2 minutes. Open Linkable on Android and connect to this desktop.",
    "devices.reconnect.ready": "Automatic reconnect is allowed again for this phone.",
    "devices.disconnect.done": "This phone was disconnected. Automatic reconnect is paused.",
    "devices.unpair.done": "Auto-reconnect is paused for this phone. Click Reconnect to allow it again.",
    "devices.forget.done": "The phone was forgotten. It can pair again later as a new device.",
    "devices.empty.title": "No paired phones",
    "devices.empty.body": "Open Linkable on Android, scan this desktop, then enter the pairing code here.",
    "devices.connected": "Connected",
    "devices.unavailable": "Unavailable",
    "devices.manual": "Disconnected by user",
    "devices.lan": "LAN",
    "devices.bt": "Bluetooth",
    "devices.no_bt": "No BT",
    "devices.disconnect": "Disconnect",
    "devices.allow": "Allow reconnect",
    "devices.unpair": "Unpair",
    "devices.unpair.confirm": "Pause trusted auto-reconnect for this phone? The device will stay known and can reconnect when you click Reconnect.",
    "devices.forget": "Forget",
    "devices.forget.confirm": "Forget this phone on this PC? This clears trust and desktop-side settings, but does not block future pairing.",
    "devices.paired_at": "Paired {timestamp}",
    "devices.endpoint_unknown": "Endpoint: xxxx..",
    "devices.id": "ID: {device_id}",
    "devices.endpoint": "Endpoint: {endpoint}",
    "devices.settings.title": "Settings/{name}",
    "devices.notifications.title": "Notifications/{name}",
    "devices.action.settings": "Device settings",
    "devices.action.notifications": "Notifications",
    "devices.action.reconnect": "Reconnect",
    "devices.action.unpair": "Unpair",
    "devices.action.forget": "Forget",
    "devices.action.ring": "Ring",
    "devices.action.stop_ring": "Stop ring",
    "devices.action.call": "Phone Call",
    "devices.action.contacts": "Contacts",
    "devices.action.files": "Browse Files",
    "devices.action.send_file": "Send File",
    "devices.action.mirror": "Mirror",
    "devices.action.shared_apps": "Shared Apps",
    "devices.status.lan": "LAN connected",
    "devices.status.offline": "LAN offline",
    "devices.status.lan_bt": "LAN and Bluetooth connected",
    "safe_wifi.title": "Safe Wi-Fi",
    "safe_wifi.allow_all": "Allow pairing on all Wi-Fi",
    "safe_wifi.current": "Current Wi-Fi: {ssid}",
    "safe_wifi.current_missing": "Current Wi-Fi could not be detected.",
    "safe_wifi.empty": "No desktop safe Wi-Fi networks recorded.",
    "notifications.title": "Notifications",
    "notifications.center.open": "Notification center",
    "notifications.center.title": "Phone notifications",
    "notifications.center.subtitle": "Everything received from the phone, plus recent call events.",
    "notifications.center.phone_section": "Received notifications",
    "notifications.center.call_section": "Call history",
    "notifications.subtitle": "Mirrored phone notifications grouped by app.",
    "notifications.empty": "No phone notifications have arrived yet.",
    "notifications.calls.empty": "No call events have arrived yet.",
    "notifications.unknown_app": "Unknown app",
    "notifications.default_title": "Notification",
    "notifications.reply": "Reply",
    "notifications.run_action": "Run action",
    "notifications.copy_text": "Copy text",
    "notifications.copy_otp": "Copy OTP",
    "notifications.clear": "Clear",
    "notifications.clear_all": "Clear all",
    "notifications.no_otp": "No OTP-like code found.",
    "files.title": "Files",
    "files.subtitle": "Send files to the connected phone and review files received from it.",
    "files.send": "Send file to phone",
    "files.browse_phone": "Browse phone",
    "files.phone_browser": "Phone browser",
    "files.transfer_actions": "Transfers",
    "files.location": "Location",
    "files.go": "Go",
    "files.root": "Root",
    "files.up": "Up",
    "files.refresh_folder": "Refresh folder",
    "files.pull": "Copy from phone",
    "files.open_folder": "Open folder",
    "files.copy_selected": "Copy selected file",
    "files.open_received": "Open received folder",
    "files.bytes": "{size} bytes",
    "files.received": "Received files",
    "files.empty": "No received files in Downloads/Linkable yet.",
    "files.no_phone_folder": "No phone folder loaded. Connect a phone and click Root.",
    "files.current_folder": "Current folder",
    "files.column.name": "Name",
    "files.column.type": "Type",
    "files.column.size": "Size",
    "files.column.modified": "Modified",
    "files.type_folder": "Folder",
    "files.type_file": "File",
    "files.error": "Error",
    "files.empty_folder": "This folder is empty.",
    "files.item_count": "{count} items",
    "files.context.open": "Open folder",
    "files.context.copy": "Copy",
    "files.context.send_laptop": "Send to Laptop",
    "mirror.title": "Mirror",
    "mirror.subtitle": "Launch scrcpy over USB first or the current LAN phone IP.",
    "mirror.refresh": "Refresh ADB",
    "mirror.usb": "Mirror USB",
    "mirror.lan": "Mirror LAN",
    "mirror.choose": "Choose mirror method",
    "mirror.choose.body": "USB and LAN mirroring are both available. Choose the route to use.",
    "calls.title": "Phone Call",
    "calls.subtitle": "Search phone contacts, dial through the phone, and manage call audio.",
    "calls.dialer": "Dialer",
    "calls.contacts": "Contacts",
    "calls.contact_search": "Search contacts from connected phone",
    "calls.contact_search_disabled": "Connect a phone to search contacts",
    "calls.search_results": "Search results",
    "calls.search_hint": "Start typing to request matching contacts from the phone.",
    "calls.no_search_results": "No matching contacts returned yet.",
    "calls.recent_contacts": "Recent contacts",
    "calls.no_recents": "Recent contacts will load after the phone connects.",
    "calls.use_contact": "Use",
    "calls.ring": "Ring phone",
    "calls.stop_ring": "Stop ring",
    "calls.accept": "Accept",
    "calls.reject": "Reject",
    "calls.hangup": "Hang up",
    "calls.dial": "Dial",
    "calls.dial_sim_1": "Dial SIM 1",
    "calls.dial_sim_2": "Dial SIM 2",
    "calls.number": "Phone number",
    "calls.sim": "SIM",
    "calls.diagnostics": "Refresh phone diagnostics",
    "calls.speaker": "Speaker volume",
    "calls.microphone": "Microphone volume",
    "calls.status": "Call controls",
    "shared_apps.title": "Shared Apps",
    "shared_apps.subtitle": "Phone-published app shortcuts grouped by category.",
    "shared_apps.empty": "No shared apps have been received from the phone. Select apps on Android under the target PC.",
    "shared_apps.other": "Other",
    "shared_apps.launch": "Launch",
    "settings.camera": "Camera Share",
    "settings.camera.usb": "Over USB",
    "settings.camera.lan": "Over LAN",
    "settings.camera.test": "Camera test",
    "settings.camera.front": "Front",
    "settings.camera.back": "Back",
    "settings.camera.switch": "Switch camera",
    "settings.camera.on": "Camera On",
    "settings.camera.test.title": "Camera test",
    "settings.camera.alive": "Camera stream is controlled by this popup. Closing it stops the phone camera and Linkable Camera feed.",
    "settings.camera.close_feed": "Close camera feed",
    "settings.camera.waiting": "Waiting for phone camera frames...",
    "settings.camera.switching": "Switching phone camera...",
    "settings.camera.bad_frame": "Received a camera frame that could not be decoded.",
    "settings.camera.virtual.starting": "Preparing Linkable Camera...",
    "settings.camera.virtual.active": "Feeding phone camera into {device} as Linkable Camera.",
    "settings.camera.virtual.failed": "Linkable Camera is not available.",
    "settings.camera.virtual.detail": "Keep this popup open, then select 'Linkable Camera' in video-call, browser, OBS, or camera-test apps. A placeholder feed keeps the device visible until phone frames arrive.",
    "settings.camera.virtual.frames": "Frames: {count}",
    "settings.camera.virtual.frames.detail": "Frames received: {received}; frames written to Linkable Camera: {written}",
    "settings.camera.test.preview_waiting": "Waiting for Linkable Camera preview...",
    "settings.camera.test.stats": "Phone sent: {sent}; desktop received: {received}; Linkable written: {written}; preview read: {preview}",
    "settings.camera.devices": "PC video devices:\n{devices}",
    "settings.camera.copy_setup": "Copy setup command",
    "settings.input": "Control Input",
    "settings.input.enable": "Enable Control Input",
    "settings.input.keyboard": "Keyboard",
    "settings.input.mouse": "Mouse",
    "settings.input.commands": "Commands Input",
    "settings.frontend_only": "Frontend-only controls. Backend wiring will be added later.",
    "settings.backend_live": "Camera sharing and control-input preferences are saved per device.",
    "common.open": "Open",
    "common.back": "Back",
    "common.close": "Close",
    "pairing.title": "Pair phone",
    "pairing.allow": "Allow pairing request from {name} ({device_id}) at {address}?",
    "pairing.code": "Enter the 6-digit code shown on the phone.",
    "common.cancel": "Cancel",
    "common.ok": "OK",
}


def tr(key: str, **kwargs: object) -> str:
    """Return an i18n-ready UI string."""

    value = STRINGS.get(key, key)
    if kwargs:
        return value.format(**kwargs)
    return value
