# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apps.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'apps.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\napps.proto\x12\x14linkable.protocol.v1\x1a\x0c\x63ommon.proto\"o\n\x11SharedAppShortcut\x12\x14\n\x0cpackage_name\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x10\n\x08icon_png\x18\x04 \x01(\x0c\x12\x11\n\ticon_mime\x18\x05 \x01(\t\"\x97\x01\n\x12SharedAppsSnapshot\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t\x12\x35\n\x04\x61pps\x18\x02 \x03(\x0b\x32\'.linkable.protocol.v1.SharedAppShortcut\x12\x35\n\x0cgenerated_at\x18\x03 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\"y\n\x16SharedAppLaunchRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x14\n\x0cpackage_name\x18\x02 \x01(\t\x12\x35\n\x0crequested_at\x18\x03 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\"\x99\x01\n\x15SharedAppLaunchResult\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x14\n\x0cpackage_name\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x04 \x01(\t\x12\x35\n\x0c\x63ompleted_at\x18\x05 \x01(\x0b\x32\x1f.linkable.protocol.v1.TimestampB\'\n\x18\x63om.linkable.protocol.v1B\tAppsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apps_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.linkable.protocol.v1B\tAppsProtoP\001'
  _globals['_SHAREDAPPSHORTCUT']._serialized_start=50
  _globals['_SHAREDAPPSHORTCUT']._serialized_end=161
  _globals['_SHAREDAPPSSNAPSHOT']._serialized_start=164
  _globals['_SHAREDAPPSSNAPSHOT']._serialized_end=315
  _globals['_SHAREDAPPLAUNCHREQUEST']._serialized_start=317
  _globals['_SHAREDAPPLAUNCHREQUEST']._serialized_end=438
  _globals['_SHAREDAPPLAUNCHRESULT']._serialized_start=441
  _globals['_SHAREDAPPLAUNCHRESULT']._serialized_end=594
# @@protoc_insertion_point(module_scope)
