# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clipboard.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'clipboard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63lipboard.proto\x12\x14linkable.protocol.v1\x1a\x0c\x63ommon.proto\"\xc5\x01\n\x0f\x43lipboardUpdate\x12\x11\n\tupdate_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x11\n\tmime_type\x18\x03 \x01(\t\x12\x13\n\x0btext_length\x18\x04 \x01(\r\x12\x33\n\nupdated_at\x18\x05 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\x12\x18\n\x10source_device_id\x18\x06 \x01(\t\x12\x1a\n\x12source_device_name\x18\x07 \x01(\tB,\n\x18\x63om.linkable.protocol.v1B\x0e\x43lipboardProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clipboard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.linkable.protocol.v1B\016ClipboardProtoP\001'
  _globals['_CLIPBOARDUPDATE']._serialized_start=56
  _globals['_CLIPBOARDUPDATE']._serialized_end=253
# @@protoc_insertion_point(module_scope)
