# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contacts.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'contacts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ontacts.proto\x12\x14linkable.protocol.v1\x1a\x0c\x63ommon.proto\"\x80\x01\n\x0cPhoneContact\x12\x12\n\ncontact_id\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x14\n\x0cphone_number\x18\x03 \x01(\t\x12\r\n\x05label\x18\x04 \x01(\t\x12!\n\x19last_interaction_epoch_ms\x18\x05 \x01(\x03\"\x7f\n\x14PhoneContactsRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\r\x12\x35\n\x0crequested_at\x18\x04 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\"\xb9\x01\n\x15PhoneContactsResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\x12\x34\n\x08\x63ontacts\x18\x04 \x03(\x0b\x32\".linkable.protocol.v1.PhoneContact\x12\x35\n\x0c\x63ompleted_at\x18\x05 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\"v\n\x1aPhoneRecentContactsRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\r\x12\x35\n\x0crequested_at\x18\x03 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\"\xbf\x01\n\x1bPhoneRecentContactsResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\x12\x34\n\x08\x63ontacts\x18\x04 \x03(\x0b\x32\".linkable.protocol.v1.PhoneContact\x12\x35\n\x0c\x63ompleted_at\x18\x05 \x01(\x0b\x32\x1f.linkable.protocol.v1.TimestampB+\n\x18\x63om.linkable.protocol.v1B\rContactsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contacts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.linkable.protocol.v1B\rContactsProtoP\001'
  _globals['_PHONECONTACT']._serialized_start=55
  _globals['_PHONECONTACT']._serialized_end=183
  _globals['_PHONECONTACTSREQUEST']._serialized_start=185
  _globals['_PHONECONTACTSREQUEST']._serialized_end=312
  _globals['_PHONECONTACTSRESPONSE']._serialized_start=315
  _globals['_PHONECONTACTSRESPONSE']._serialized_end=500
  _globals['_PHONERECENTCONTACTSREQUEST']._serialized_start=502
  _globals['_PHONERECENTCONTACTSREQUEST']._serialized_end=620
  _globals['_PHONERECENTCONTACTSRESPONSE']._serialized_start=623
  _globals['_PHONERECENTCONTACTSRESPONSE']._serialized_end=814
# @@protoc_insertion_point(module_scope)
