# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: errors.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'errors.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65rrors.proto\x12\x14linkable.protocol.v1\x1a\x0c\x63ommon.proto\"\xbd\x01\n\x0c\x45rrorPayload\x12-\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1f.linkable.protocol.v1.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05\x66\x61tal\x18\x03 \x01(\x08\x12=\n\x13related_packet_type\x18\x04 \x01(\x0e\x32 .linkable.protocol.v1.PacketType\x12\x1f\n\x17related_sequence_number\x18\x05 \x01(\x04*\xaf\x04\n\tErrorCode\x12\x1a\n\x16\x45RROR_CODE_UNSPECIFIED\x10\x00\x12)\n$ERROR_CODE_PROTOCOL_VERSION_MISMATCH\x10\xe9\x07\x12#\n\x1e\x45RROR_CODE_INVALID_PACKET_TYPE\x10\xea\x07\x12!\n\x1c\x45RROR_CODE_MALFORMED_PAYLOAD\x10\xeb\x07\x12\x1f\n\x1a\x45RROR_CODE_SEQUENCE_REPLAY\x10\xec\x07\x12\x1c\n\x17\x45RROR_CODE_SEQUENCE_GAP\x10\xed\x07\x12#\n\x1e\x45RROR_CODE_PAIRING_NOT_ALLOWED\x10\xd1\x0f\x12\x1f\n\x1a\x45RROR_CODE_PAIRING_TIMEOUT\x10\xd2\x0f\x12%\n ERROR_CODE_PAIRING_CODE_MISMATCH\x10\xd3\x0f\x12\x1f\n\x1a\x45RROR_CODE_TRUST_NOT_FOUND\x10\xd4\x0f\x12\'\n\"ERROR_CODE_SESSION_NOT_ESTABLISHED\x10\xb9\x17\x12)\n$ERROR_CODE_SESSION_SIGNATURE_INVALID\x10\xba\x17\x12-\n(ERROR_CODE_SESSION_KEY_ROTATION_REQUIRED\x10\xbb\x17\x12!\n\x1c\x45RROR_CODE_HEARTBEAT_TIMEOUT\x10\xbc\x17\x12 \n\x1b\x45RROR_CODE_INTERNAL_FAILURE\x10\xa9\x46\x42)\n\x18\x63om.linkable.protocol.v1B\x0b\x45rrorsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'errors_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.linkable.protocol.v1B\013ErrorsProtoP\001'
  _globals['_ERRORCODE']._serialized_start=245
  _globals['_ERRORCODE']._serialized_end=804
  _globals['_ERRORPAYLOAD']._serialized_start=53
  _globals['_ERRORPAYLOAD']._serialized_end=242
# @@protoc_insertion_point(module_scope)
