# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: files.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'files.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66iles.proto\x12\x14linkable.protocol.v1\x1a\x0c\x63ommon.proto\"\xb7\x01\n\tFileOffer\x12\x13\n\x0btransfer_id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x12\n\nsize_bytes\x18\x03 \x01(\x04\x12\x12\n\nsha256_hex\x18\x04 \x01(\t\x12\x11\n\tmime_type\x18\x05 \x01(\t\x12\x12\n\nchunk_size\x18\x06 \x01(\r\x12\x33\n\noffered_at\x18\x07 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\">\n\tFileChunk\x12\x13\n\x0btransfer_id\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"7\n\x0c\x46ileComplete\x12\x13\n\x0btransfer_id\x18\x01 \x01(\t\x12\x12\n\nsha256_hex\x18\x02 \x01(\t\"\xad\x01\n\x12\x46ileTransferResult\x12\x13\n\x0btransfer_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\x12\x12\n\nsaved_path\x18\x04 \x01(\t\x12\x16\n\x0e\x62ytes_received\x18\x05 \x01(\x04\x12\x35\n\x0c\x63ompleted_at\x18\x06 \x01(\x0b\x32\x1f.linkable.protocol.v1.TimestampB(\n\x18\x63om.linkable.protocol.v1B\nFilesProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'files_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.linkable.protocol.v1B\nFilesProtoP\001'
  _globals['_FILEOFFER']._serialized_start=52
  _globals['_FILEOFFER']._serialized_end=235
  _globals['_FILECHUNK']._serialized_start=237
  _globals['_FILECHUNK']._serialized_end=299
  _globals['_FILECOMPLETE']._serialized_start=301
  _globals['_FILECOMPLETE']._serialized_end=356
  _globals['_FILETRANSFERRESULT']._serialized_start=359
  _globals['_FILETRANSFERRESULT']._serialized_end=532
# @@protoc_insertion_point(module_scope)
