# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: input.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'input.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0binput.proto\x12\x14linkable.protocol.v1\x1a\x0c\x63ommon.proto\"\xbc\x02\n\x13\x44\x65sktopInputRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x41\n\x0b\x61\x63tion_type\x18\x02 \x01(\x0e\x32,.linkable.protocol.v1.DesktopInputActionType\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x11\n\tkey_combo\x18\x04 \x03(\t\x12\x12\n\npointer_dx\x18\x05 \x01(\x05\x12\x12\n\npointer_dy\x18\x06 \x01(\x05\x12\x16\n\x0epointer_button\x18\x07 \x01(\x05\x12\x10\n\x08scroll_y\x18\x08 \x01(\x05\x12\x16\n\x0evolume_percent\x18\t \x01(\x05\x12\x11\n\tmic_muted\x18\n \x01(\x08\x12\x30\n\x07sent_at\x18\x0b \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\"\x80\x01\n\x12\x44\x65sktopInputResult\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\x12\x35\n\x0c\x63ompleted_at\x18\x04 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp*\xed\x02\n\x16\x44\x65sktopInputActionType\x12)\n%DESKTOP_INPUT_ACTION_TYPE_UNSPECIFIED\x10\x00\x12\"\n\x1e\x44\x45SKTOP_INPUT_ACTION_TYPE_TEXT\x10\x01\x12\'\n#DESKTOP_INPUT_ACTION_TYPE_KEY_COMBO\x10\x02\x12*\n&DESKTOP_INPUT_ACTION_TYPE_POINTER_MOVE\x10\x03\x12+\n\'DESKTOP_INPUT_ACTION_TYPE_POINTER_CLICK\x10\x04\x12,\n(DESKTOP_INPUT_ACTION_TYPE_POINTER_SCROLL\x10\x05\x12(\n$DESKTOP_INPUT_ACTION_TYPE_VOLUME_SET\x10\x06\x12*\n&DESKTOP_INPUT_ACTION_TYPE_MIC_MUTE_SET\x10\x07\x42(\n\x18\x63om.linkable.protocol.v1B\nInputProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'input_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.linkable.protocol.v1B\nInputProtoP\001'
  _globals['_DESKTOPINPUTACTIONTYPE']._serialized_start=502
  _globals['_DESKTOPINPUTACTIONTYPE']._serialized_end=867
  _globals['_DESKTOPINPUTREQUEST']._serialized_start=52
  _globals['_DESKTOPINPUTREQUEST']._serialized_end=368
  _globals['_DESKTOPINPUTRESULT']._serialized_start=371
  _globals['_DESKTOPINPUTRESULT']._serialized_end=499
# @@protoc_insertion_point(module_scope)
