# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pairing.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'pairing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpairing.proto\x12\x14linkable.protocol.v1\x1a\x0c\x63ommon.proto\"x\n\x0ePairingRequest\x12\x37\n\tinitiator\x18\x01 \x01(\x0b\x32$.linkable.protocol.v1.PeerDescriptor\x12\x15\n\rpairing_nonce\x18\x02 \x01(\x0c\x12\x16\n\x0e\x64irect_connect\x18\x03 \x01(\x08\"\xa4\x01\n\x10PairingChallenge\x12\x36\n\x08\x61\x63\x63\x65ptor\x18\x01 \x01(\x0b\x32$.linkable.protocol.v1.PeerDescriptor\x12\x17\n\x0f\x63hallenge_nonce\x18\x02 \x01(\x0c\x12 \n\x18verification_code_length\x18\x03 \x01(\r\x12\x1d\n\x15\x63ode_derivation_label\x18\x04 \x01(\t\"\x80\x01\n\x0ePairingConfirm\x12\x37\n\tconfirmer\x18\x01 \x01(\x0b\x32$.linkable.protocol.v1.PeerDescriptor\x12\x17\n\x0ftranscript_hash\x18\x02 \x01(\x0c\x12\x1c\n\x14transcript_signature\x18\x03 \x01(\x0c\"\x81\x01\n\x0fPairingComplete\x12:\n\x0ctrusted_peer\x18\x01 \x01(\x0b\x32$.linkable.protocol.v1.PeerDescriptor\x12\x32\n\tpaired_at\x18\x02 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\"Z\n\rPairingReject\x12\x39\n\x06reason\x18\x01 \x01(\x0e\x32).linkable.protocol.v1.PairingRejectReason\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t*\xb4\x02\n\x13PairingRejectReason\x12%\n!PAIRING_REJECT_REASON_UNSPECIFIED\x10\x00\x12\'\n#PAIRING_REJECT_REASON_USER_DECLINED\x10\x01\x12\'\n#PAIRING_REJECT_REASON_CODE_MISMATCH\x10\x02\x12+\n\'PAIRING_REJECT_REASON_PROTOCOL_MISMATCH\x10\x03\x12!\n\x1dPAIRING_REJECT_REASON_TIMEOUT\x10\x04\x12*\n&PAIRING_REJECT_REASON_DUPLICATE_DEVICE\x10\x05\x12(\n$PAIRING_REJECT_REASON_INTERNAL_ERROR\x10\x06\x42*\n\x18\x63om.linkable.protocol.v1B\x0cPairingProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pairing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.linkable.protocol.v1B\014PairingProtoP\001'
  _globals['_PAIRINGREJECTREASON']._serialized_start=698
  _globals['_PAIRINGREJECTREASON']._serialized_end=1006
  _globals['_PAIRINGREQUEST']._serialized_start=53
  _globals['_PAIRINGREQUEST']._serialized_end=173
  _globals['_PAIRINGCHALLENGE']._serialized_start=176
  _globals['_PAIRINGCHALLENGE']._serialized_end=340
  _globals['_PAIRINGCONFIRM']._serialized_start=343
  _globals['_PAIRINGCONFIRM']._serialized_end=471
  _globals['_PAIRINGCOMPLETE']._serialized_start=474
  _globals['_PAIRINGCOMPLETE']._serialized_end=603
  _globals['_PAIRINGREJECT']._serialized_start=605
  _globals['_PAIRINGREJECT']._serialized_end=695
# @@protoc_insertion_point(module_scope)
