# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: session.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsession.proto\x12\x14linkable.protocol.v1\x1a\x0c\x63ommon.proto\"\xb4\x01\n\x0bSessionInit\x12\x37\n\tinitiator\x18\x01 \x01(\x0b\x32$.linkable.protocol.v1.PeerDescriptor\x12\x1c\n\x14\x65phemeral_public_key\x18\x02 \x01(\x0c\x12\x1a\n\x12identity_signature\x18\x03 \x01(\x0c\x12\x32\n\tissued_at\x18\x04 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\"\xb2\x01\n\nSessionAck\x12\x36\n\x08\x61\x63\x63\x65ptor\x18\x01 \x01(\x0b\x32$.linkable.protocol.v1.PeerDescriptor\x12\x1c\n\x14\x65phemeral_public_key\x18\x02 \x01(\x0c\x12\x1a\n\x12identity_signature\x18\x03 \x01(\x0c\x12\x32\n\tissued_at\x18\x04 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\"\x98\x01\n\rSessionRotate\x12\x30\n\x0crequested_by\x18\x01 \x01(\x0e\x32\x1a.linkable.protocol.v1.Role\x12!\n\x19next_ephemeral_public_key\x18\x02 \x01(\x0c\x12\x16\n\x0erotation_epoch\x18\x03 \x01(\x04\x12\x1a\n\x12identity_signature\x18\x04 \x01(\x0c\"X\n\x0cSessionClose\x12\x38\n\x06reason\x18\x01 \x01(\x0e\x32(.linkable.protocol.v1.SessionCloseReason\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t*\xf2\x01\n\x12SessionCloseReason\x12$\n SESSION_CLOSE_REASON_UNSPECIFIED\x10\x00\x12\x1f\n\x1bSESSION_CLOSE_REASON_NORMAL\x10\x01\x12 \n\x1cSESSION_CLOSE_REASON_TIMEOUT\x10\x02\x12 \n\x1cSESSION_CLOSE_REASON_REVOKED\x10\x03\x12\'\n#SESSION_CLOSE_REASON_PROTOCOL_ERROR\x10\x04\x12(\n$SESSION_CLOSE_REASON_TRANSPORT_ERROR\x10\x05\x42*\n\x18\x63om.linkable.protocol.v1B\x0cSessionProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.linkable.protocol.v1B\014SessionProtoP\001'
  _globals['_SESSIONCLOSEREASON']._serialized_start=663
  _globals['_SESSIONCLOSEREASON']._serialized_end=905
  _globals['_SESSIONINIT']._serialized_start=54
  _globals['_SESSIONINIT']._serialized_end=234
  _globals['_SESSIONACK']._serialized_start=237
  _globals['_SESSIONACK']._serialized_end=415
  _globals['_SESSIONROTATE']._serialized_start=418
  _globals['_SESSIONROTATE']._serialized_end=570
  _globals['_SESSIONCLOSE']._serialized_start=572
  _globals['_SESSIONCLOSE']._serialized_end=660
# @@protoc_insertion_point(module_scope)
