# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\x12\x14linkable.protocol.v1\x1a\x0c\x63ommon.proto\"\x81\x01\n\x0ePhoneFileEntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x11\n\tdirectory\x18\x03 \x01(\x08\x12\x12\n\nsize_bytes\x18\x04 \x01(\x04\x12\x11\n\tmime_type\x18\x05 \x01(\t\x12\x19\n\x11modified_epoch_ms\x18\x06 \x01(\x03\"o\n\x14PhoneFileListRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x35\n\x0crequested_at\x18\x03 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\"\xc8\x01\n\x15PhoneFileListResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x04 \x01(\t\x12\x35\n\x07\x65ntries\x18\x05 \x03(\x0b\x32$.linkable.protocol.v1.PhoneFileEntry\x12\x35\n\x0c\x63ompleted_at\x18\x06 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\"o\n\x14PhoneFilePullRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x35\n\x0crequested_at\x18\x03 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\"\x8f\x01\n\x13PhoneFilePullResult\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x04 \x01(\t\x12\x35\n\x0c\x63ompleted_at\x18\x05 \x01(\x0b\x32\x1f.linkable.protocol.v1.TimestampB*\n\x18\x63om.linkable.protocol.v1B\x0cStorageProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.linkable.protocol.v1B\014StorageProtoP\001'
  _globals['_PHONEFILEENTRY']._serialized_start=54
  _globals['_PHONEFILEENTRY']._serialized_end=183
  _globals['_PHONEFILELISTREQUEST']._serialized_start=185
  _globals['_PHONEFILELISTREQUEST']._serialized_end=296
  _globals['_PHONEFILELISTRESPONSE']._serialized_start=299
  _globals['_PHONEFILELISTRESPONSE']._serialized_end=499
  _globals['_PHONEFILEPULLREQUEST']._serialized_start=501
  _globals['_PHONEFILEPULLREQUEST']._serialized_end=612
  _globals['_PHONEFILEPULLRESULT']._serialized_start=615
  _globals['_PHONEFILEPULLRESULT']._serialized_end=758
# @@protoc_insertion_point(module_scope)
