# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'transport.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftransport.proto\x12\x14linkable.protocol.v1\x1a\x0c\x63ommon.proto\"G\n\x04Ping\x12\r\n\x05token\x18\x01 \x01(\t\x12\x30\n\x07sent_at\x18\x02 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\"}\n\x04Pong\x12\r\n\x05token\x18\x01 \x01(\t\x12\x30\n\x07sent_at\x18\x02 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\x12\x34\n\x0breceived_at\x18\x03 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\"\x13\n\x11\x44\x65viceInfoRequest\"\xc1\x01\n\x12\x44\x65viceInfoResponse\x12\x32\n\x04peer\x18\x01 \x01(\x0b\x32$.linkable.protocol.v1.PeerDescriptor\x12\x12\n\nos_version\x18\x02 \x01(\t\x12\x17\n\x0f\x62\x61ttery_present\x18\x03 \x01(\x08\x12\x17\n\x0f\x62\x61ttery_percent\x18\x04 \x01(\x05\x12\x15\n\rscreen_locked\x18\x05 \x01(\x08\x12\x1a\n\x12network_interfaces\x18\x06 \x03(\t\";\n\nCapability\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\"\x15\n\x13\x43\x61pabilitiesRequest\"N\n\x14\x43\x61pabilitiesResponse\x12\x36\n\x0c\x63\x61pabilities\x18\x01 \x03(\x0b\x32 .linkable.protocol.v1.Capability\"n\n\tHeartbeat\x12\x30\n\x07sent_at\x18\x01 \x01(\x0b\x32\x1f.linkable.protocol.v1.Timestamp\x12/\n\x0bsender_role\x18\x02 \x01(\x0e\x32\x1a.linkable.protocol.v1.RoleB,\n\x18\x63om.linkable.protocol.v1B\x0eTransportProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.linkable.protocol.v1B\016TransportProtoP\001'
  _globals['_PING']._serialized_start=55
  _globals['_PING']._serialized_end=126
  _globals['_PONG']._serialized_start=128
  _globals['_PONG']._serialized_end=253
  _globals['_DEVICEINFOREQUEST']._serialized_start=255
  _globals['_DEVICEINFOREQUEST']._serialized_end=274
  _globals['_DEVICEINFORESPONSE']._serialized_start=277
  _globals['_DEVICEINFORESPONSE']._serialized_end=470
  _globals['_CAPABILITY']._serialized_start=472
  _globals['_CAPABILITY']._serialized_end=531
  _globals['_CAPABILITIESREQUEST']._serialized_start=533
  _globals['_CAPABILITIESREQUEST']._serialized_end=554
  _globals['_CAPABILITIESRESPONSE']._serialized_start=556
  _globals['_CAPABILITIESRESPONSE']._serialized_end=634
  _globals['_HEARTBEAT']._serialized_start=636
  _globals['_HEARTBEAT']._serialized_end=746
# @@protoc_insertion_point(module_scope)
